version: '3.7'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:ro
    ports:
      - "1883:1883"
      - "9001:9001"

  iot_data_generator:
    build: ./iot_data_generator
    command: python run.py
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
      - INTERVAL_MS=1000
      - LOGGING_LEVEL=20
    depends_on:
      - mqtt_broker
  
  data_processor:
    build: ./data_processor
    command: python mqtt_to_parquet.py
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
    depends_on:
      - mqtt_broker
    volumes:
      - ./raw_json_data:/app/raw_json_data
      - ./parquet_tables:/app/parquet_tables

volumes:
  data: ~
